name: Backend Docker Build & Push

on:
  push:
    paths:
      - 'Back-end/**'   # Trigger only when backend changes
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      - name: Build Spring Boot Jar
        run: |
          cd Back-end
          mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          cd Back-end
          docker build -t riteshkumarv/social-media-backend:latest .

      - name: Push Docker image
        run: docker push riteshkumarv/social-media-backend:latest
